"""
Payment receipt generation — a clean, professional single-page PDF, built
with reportlab's Platypus (structured document) API rather than raw canvas
drawing, since a receipt has clear sections (header, details, footer) that
map naturally onto flowable elements.
"""

import io
from datetime import datetime, timezone
from decimal import Decimal

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_RIGHT, TA_CENTER

INK_900 = colors.HexColor("#16213D")
INK_600 = colors.HexColor("#3D5280")
EMERALD_700 = colors.HexColor("#16543C")


def generate_receipt_pdf(
    receipt_number: str,
    school_name: str,
    student_name: str,
    admission_number: str,
    amount: Decimal,
    currency: str,
    method: str,
    reference_code: str | None,
    paid_at: datetime | None,
    invoice_total: Decimal | None,
    invoice_balance_after: Decimal | None,
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
        leftMargin=25 * mm,
        rightMargin=25 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReceiptTitle", parent=styles["Title"], textColor=INK_900, fontSize=20, spaceAfter=2)
    subtitle_style = ParagraphStyle("ReceiptSubtitle", parent=styles["Normal"], textColor=INK_600, fontSize=10)
    label_style = ParagraphStyle("Label", parent=styles["Normal"], textColor=INK_600, fontSize=9)
    amount_style = ParagraphStyle(
        "Amount", parent=styles["Normal"], textColor=EMERALD_700, fontSize=26, alignment=TA_CENTER, spaceBefore=4, spaceAfter=4
    )
    footer_style = ParagraphStyle("Footer", parent=styles["Normal"], textColor=INK_600, fontSize=8, alignment=TA_CENTER)

    def fmt_money(amt: Decimal) -> str:
        return f"{currency} {amt:,.2f}"

    story = []

    story.append(Paragraph(school_name, title_style))
    story.append(Paragraph("Payment Receipt", subtitle_style))
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E4E2DA")))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Amount received", label_style))
    story.append(Paragraph(fmt_money(amount), amount_style))
    story.append(Spacer(1, 6 * mm))

    method_labels = {
        "MPESA": "M-Pesa",
        "BANK_TRANSFER": "Bank Transfer",
        "CASH": "Cash",
        "CARD": "Card",
        "CHEQUE": "Cheque",
        "OTHER": "Other",
    }

    paid_at_str = paid_at.strftime("%d %B %Y, %H:%M") if paid_at else "—"
    details = [
        ["Receipt No.", receipt_number],
        ["Student", f"{student_name} ({admission_number})"],
        ["Date paid", paid_at_str],
        ["Payment method", method_labels.get(method.upper(), method.replace("_", " ").title())],
    ]
    if reference_code:
        details.append(["Reference", reference_code])
    if invoice_total is not None:
        details.append(["Invoice total", fmt_money(invoice_total)])
    if invoice_balance_after is not None:
        details.append(["Balance remaining", fmt_money(invoice_balance_after)])

    table = Table(details, colWidths=[45 * mm, 105 * mm])
    table.setStyle(
        TableStyle(
            [
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("TEXTCOLOR", (0, 0), (0, -1), INK_600),
                ("TEXTCOLOR", (1, 0), (1, -1), INK_900),
                ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#E4E2DA")),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 12 * mm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E4E2DA")))
    story.append(Spacer(1, 4 * mm))
    story.append(
        Paragraph(
            f"Generated by Ledgr on {datetime.now(timezone.utc).strftime('%d %B %Y')}. "
            "This receipt confirms a payment received and recorded against the student's fee account.",
            footer_style,
        )
    )

    doc.build(story)
    return buffer.getvalue()
