"""add 2fa fields

Revision ID: c530e54f39f1
Revises: dc135ced2574
Create Date: 2026-08-17 22:52:29.181281

"""

from alembic import op
import sqlalchemy as sa

revision = "c530e54f39f1"
down_revision = "dc135ced2574"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("totp_secret", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "totp_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "totp_enabled")
    op.drop_column("users", "totp_secret")
    # ### end Alembic commands ###
